Repository upfluence/oss-components, pull requests merged in 2023-11, with the labels that each got.

#324 oss/buttons: more precise transitions
  app/styles/atoms/button.less
Labels: reviewed/ready-to-merge

#325 Disabled the save button in edition mode for attributes-panel
  addon/components/o-s-s/attributes-panel.hbs
  addon/components/o-s-s/attributes-panel.stories.js
  addon/components/o-s-s/attributes-panel.ts
  tests/integration/components/o-s-s/attributes-panel-test.ts
Labels: reviewed/ready-to-merge

#326 Adds Attribute::Base component with tests
  addon/components/o-s-s/attribute/base.hbs
  addon/components/o-s-s/attribute/base.ts
  addon/components/o-s-s/attribute/country.hbs
  addon/components/o-s-s/attribute/text.hbs
  addon/components/o-s-s/attribute/text.ts
  app/components/o-s-s/attribute/base.js
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/attribute/base-test.ts
  tests/integration/components/o-s-s/attribute/text-test.ts
Labels: reviewed/needs-review

#327 Adds OSS::Attribute::RevealableEmail + tests + docs
  addon/components/o-s-s/attribute/country.stories.js
  addon/components/o-s-s/attribute/revealable-email.hbs
  addon/components/o-s-s/attribute/revealable-email.stories.js
  addon/components/o-s-s/attribute/revealable-email.ts
  addon/components/o-s-s/attribute/text.hbs
  addon/components/o-s-s/attribute/text.stories.js
  addon/components/o-s-s/attribute/text.ts
  app/components/o-s-s/attribute/revealable-email.js
  app/styles/atoms/attribute.less
  tests/dummy/app/controllers/application.js
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/attribute/revealable-email-test.ts
  translations/en-us.yaml
Labels: reviewed/needs-review

#328 Updated: inputContainer's prefix & suffix padding and suffix hitbox
  app/styles/atoms/input-container.less
  tests/dummy/app/templates/application.hbs
Labels: reviewed/ready-to-merge

#329 Improve padding in attribute panel
  app/styles/organisms/attributes-panel.less
Labels: reviewed/ready-to-merge

#330 Adds OSS::Attribute::PhoneNumber along with documentation and tests
  addon/components/o-s-s/attribute/phone-number.hbs
  addon/components/o-s-s/attribute/phone-number.stories.js
  addon/components/o-s-s/attribute/phone-number.ts
  app/components/o-s-s/attribute/phone-number.js
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/attribute/phone-number-test.ts
  translations/en-us.yaml
Labels: reviewed/ready-to-merge

#332 Banner: Add a disable state
  addon/components/o-s-s/banner.hbs
  addon/components/o-s-s/banner.stories.js
  app/styles/banner.less
  tests/integration/components/o-s-s/banner-test.ts
Labels: reviewed/ready-to-merge

#333 Adds OSS::Attribute::TagArray component along with tests and documentation
  addon/components/o-s-s/attribute/removable-text.hbs
  addon/components/o-s-s/attribute/removable-text.stories.js
  addon/components/o-s-s/attribute/removable-text.ts
  addon/components/o-s-s/attribute/tag-array.hbs
  addon/components/o-s-s/attribute/tag-array.stories.js
  addon/components/o-s-s/attribute/tag-array.ts
  app/components/o-s-s/attribute/removable-text.js
  app/components/o-s-s/attribute/tag-array.js
  app/components/o-s-s/attribute/tagada.js
  app/styles/atoms/attribute.less
  tests/dummy/app/controllers/application.js
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/attribute/removable-text-test.ts
  tests/integration/components/o-s-s/attribute/tag-array-test.ts
  translations/en-us.yaml
Labels: reviewed/ready-to-merge

#331 Added OSS::Attribute::Rating
  addon/components/o-s-s/attribute/rating.hbs
  addon/components/o-s-s/attribute/rating.stories.js
  addon/components/o-s-s/attribute/rating.ts
  addon/components/o-s-s/star-rating.hbs
  addon/components/o-s-s/star-rating.ts
  app/components/o-s-s/attribute/rating.js
  app/styles/atoms/attribute.less
  app/styles/star-rating.less
  tests/dummy/app/controllers/application.js
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/attribute/rating-test.ts
  tests/integration/components/o-s-s/star-rating-test.ts
Labels: reviewed/needs-work

#334 Adds the ability to specify country-selector province mode with code value
  addon/components/o-s-s/country-selector.ts
  tests/dummy/app/controllers/application.js
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/country-selector-test.ts
Labels: reviewed/ready-to-merge

#335 Fixed: OSS::StarRating onClick not triggered + added tests
  addon/components/o-s-s/star-rating.hbs
  addon/components/o-s-s/star-rating.ts
  tests/dummy/app/controllers/application.js
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/star-rating-test.ts
Labels: reviewed/ready-to-merge

#336 Bump @fortawesome/fontawesome-pro to ^6.4.2
  index.js
  package.json
  yarn.lock
Labels: reviewed/ready-to-merge

#337 [Cooldow] Replace old tooltip by new one
  addon/components/upf-stat.js
  app/styles/base/_stats.less
  app/templates/components/upf-stat.hbs
  app/templates/components/upf-table/header-cell.hbs
Labels: reviewed/ready-to-merge

#338 Added OSS::ProgressBar
  addon/components/o-s-s/progress-bar.hbs
  addon/components/o-s-s/progress-bar.stories.js
  addon/components/o-s-s/progress-bar.ts
  app/components/o-s-s/progress-bar.js
  app/styles/molecules/progress-bar.less
  app/styles/oss-components.less
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/progress-bar-test.ts
Labels: reviewed/needs-review

#340 Added: option to pass custom data set to currency input + cleanup
  addon/components/o-s-s/currency-input.hbs
  addon/components/o-s-s/currency-input.stories.js
  addon/components/o-s-s/currency-input.ts
  tests/dummy/app/controllers/application.js
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/currency-input-test.ts
Labels: reviewed/needs-review

#341 Updated: OSS::Banner component with new size option + code cleanup
  addon/components/o-s-s/banner.hbs
  addon/components/o-s-s/banner.stories.js
  addon/components/o-s-s/banner.ts
  app/styles/banner.less
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/banner-test.ts
Labels: reviewed/ready-to-merge

#339 Update email regex to accept uppercase & tests
  addon/components/o-s-s/email-input.stories.js
  addon/components/o-s-s/email-input.ts
  tests/integration/components/o-s-s/email-input-test.ts
Labels: reviewed/ready-to-merge
