Repository upfluence/oss-components, pull requests merged in 2023-12, with the labels that each got.

#342 Allow null value for selectedToggle in OSS::Toggle-buttons
  addon/components/o-s-s/attribute/base.hbs
  addon/components/o-s-s/skeleton.ts
  addon/components/o-s-s/social-post-badge.stories.js
  addon/components/o-s-s/toggle-buttons.hbs
  addon/components/o-s-s/toggle-buttons.stories.js
  addon/components/o-s-s/toggle-buttons.ts
  app/styles/atoms/attribute.less
  tests/integration/components/o-s-s/attribute/text-test.ts
  tests/integration/components/o-s-s/toggle-buttons-test.ts
Labels: reviewed/ready-to-merge

#344 OSS::Banner: add support for title named-block
  addon/components/o-s-s/banner.hbs
  addon/components/o-s-s/banner.stories.js
  tests/integration/components/o-s-s/banner-test.ts
Labels: reviewed/ready-to-merge

#345 OSS::Banner: rename title named block to title-suffix
  addon/components/o-s-s/banner.hbs
  addon/components/o-s-s/banner.stories.js
  app/styles/core-v2/_variables.less
  tests/integration/components/o-s-s/banner-test.ts
Labels: reviewed/needs-review

#343 OSS::PasswordInput rework + updated tests & doc
  addon/components/o-s-s/password-input.hbs
  addon/components/o-s-s/password-input.stories.js
  addon/components/o-s-s/password-input.ts
  app/styles/molecules/password-input.less
  app/styles/oss-components.less
  package.json
  tests/dummy/app/controllers/application.js
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/password-input-test.ts
  translations/en-us.yaml
Labels: reviewed/needs-review

#348 Fixed upf-stat__label issue
  app/styles/base/_stats.less
  app/templates/components/upf-stat.hbs
Labels: reviewed/needs-work

#349 Added: OSS::ModalDialog @enqueue parameter + tests & doc
  addon/components/o-s-s/modal-dialog.hbs
  addon/components/o-s-s/modal-dialog.stories.js
  addon/components/o-s-s/modal-dialog.ts
  tests/integration/components/o-s-s/modal-dialog-test.ts
Labels: reviewed/needs-review

#352 New component OSS::Anchor
  addon/components/o-s-s/anchor.hbs
  addon/components/o-s-s/anchor.stories.js
  addon/components/o-s-s/anchor.ts
  addon/components/o-s-s/layout/sidebar.hbs
  addon/components/o-s-s/layout/sidebar/item.hbs
  addon/components/o-s-s/layout/sidebar/item.stories.js
  addon/components/o-s-s/layout/sidebar/item.ts
  addon/components/o-s-s/star-rating.hbs
  app/components/o-s-s/anchor.js
  app/styles/organisms/sidebar.less
  tests/integration/components/o-s-s/anchor-test.ts
  tests/integration/components/o-s-s/layout/sidebar/item-test.ts
Labels: reviewed/ready-to-merge
