Repository upfluence/oss-components, pull requests merged in 2023-07, with the labels that each got.

#289 Add: defaultAction & lockedAction in sidebar item
  addon/components/o-s-s/layout/sidebar.hbs
  addon/components/o-s-s/layout/sidebar/item.hbs
  addon/components/o-s-s/layout/sidebar/item.stories.js
  addon/components/o-s-s/layout/sidebar/item.ts
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/layout/sidebar/item-test.ts
Labels: reviewed/ready-to-merge

#290 Run CI on PR branches and Release tags only
  .github/workflows/ci.yml
Labels: reviewed/needs-review

#292 Add OSS:Icon & tests
  addon/components/o-s-s/icon.hbs
  addon/components/o-s-s/icon.stories.js
  addon/components/o-s-s/icon.ts
  app/components/o-s-s/icon.js
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/icon-test.ts
Labels: reviewed/needs-review

#291 Add: OSS::Skeleton component
  addon/components/o-s-s/skeleton.hbs
  addon/components/o-s-s/skeleton.stories.js
  addon/components/o-s-s/skeleton.ts
  app/components/o-s-s/skeleton.js
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/skeleton-test.ts
Labels: reviewed/ready-to-merge

#294 ENG-485: Update OSS::TogglableSection UI and add an option to display FA icons
  addon/components/o-s-s/togglable-section.hbs
  addon/components/o-s-s/togglable-section.stories.js
  addon/components/o-s-s/togglable-section.ts
  app/styles/molecules/togglable-section.less
  app/styles/oss-components.less
  tests/dummy/app/controllers/application.js
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/togglable-section-test.ts
Labels: reviewed/ready-to-merge

#295 OSS::TextArea onChange method update
  addon/components/o-s-s/text-area.hbs
  tests/integration/components/o-s-s/text-area-test.ts
Labels: reviewed/needs-work

#296 Access panel: animation support
  addon/components/o-s-s/access-panel.hbs
  addon/components/o-s-s/access-panel.ts
  app/styles/organisms/access-panel.less
Labels: reviewed/ready-to-merge

#297 Dropdown button: Add mainAction & update component
  addon/components/o-s-s/button-dropdown.hbs
  addon/components/o-s-s/button-dropdown.stories.js
  addon/components/o-s-s/button-dropdown.ts
  app/styles/molecules/button-dropdown.less
  tests/dummy/app/templates/application.hbs
  tests/integration/components/o-s-s/button-dropdown-test.ts
Labels: reviewed/ready-to-merge

#298 Remove some deaaaaaad code 🥳 🔪
  addon/components/expanding-search.hbs
  addon/components/expanding-search.js
  addon/components/upf-checkbox.js
  app/components/expanding-search.js
  app/components/upf-checkbox.js
  app/styles/base/_all.less
  app/styles/base/_expanding-search.less
  app/styles/base/_navs.less
  app/templates/components/upf-checkbox.hbs
  app/templates/components/upf-table.hbs
  tests/dummy/app/templates/application.hbs
Labels: reviewed/ready-to-merge

#299 New gradient css variable
  addon/components/o-s-s/button.stories.js
  addon/components/o-s-s/button.ts
  app/styles/atoms/button.less
  app/styles/core-v2/_colors.less
Labels: reviewed/ready-to-merge
