Repository upfluence/oss-components, pull requests merged in 2024-06, with the labels that each got.

#393 re-enable some eslint & remove mixins
  .eslintrc.js
  addon/components/app-header.js
  addon/mixins/header-style.js
  addon/mixins/upf-table-search.js
  addon/mixins/upf-table-selection.js
  app/mixins/header-style.js
  app/mixins/upf-table-search.js
  app/mixins/upf-table-selection.js
  app/styles/core-v2/_colors.less
Labels: reviewed/needs-review

#397 Remove legacy Bootstrap-powered modal component
  addon/components/o-s-s/modal.hbs
  addon/components/o-s-s/modal.js
  app/components/o-s-s/modal.js
  app/styles/shims/_bootstrap.less
  tests/integration/components/o-s-s/modal-test.js
Labels: reviewed/ready-to-merge

#396 Expose bootstrap imports
  addon/components/o-s-s/modal.hbs
  addon/components/o-s-s/modal.js
  app/components/o-s-s/modal.js
  app/styles/oss-components.less
  app/styles/shims/_bootstrap.less
  tests/integration/components/o-s-s/modal-test.js
Labels: reviewed/needs-review

#395 Replace twitter by X
  addon/components/o-s-s/iconName.enum.ts
  addon/components/o-s-s/social-post-badge.ts
  app/styles/core-v2/_colors.less
  app/styles/core-v2/_colors.stories.mdx
Labels: reviewed/needs-work

#399 Rollback bootstrap exposition
  addon/components/o-s-s/modal.hbs
  addon/components/o-s-s/modal.js
  app/components/o-s-s/modal.js
  app/styles/oss-components.less
  app/styles/shims/_bootstrap.less
  tests/integration/components/o-s-s/modal-test.js
Labels: reviewed/ready-to-merge
