Repository upfluence/oss-components, pull requests merged in 2025-04, with the labels that each got.

#487 Togglable section: Add new actions named block
  addon/components/o-s-s/togglable-section.hbs
  addon/components/o-s-s/togglable-section.stories.js
  tests/dummy/app/templates/index.hbs
  tests/integration/components/o-s-s/togglable-section-test.ts
Labels: reviewed/ready-to-merge

#485 Update toggle switch component with a check icon on active state
  addon/components/o-s-s/toggle-switch.hbs
  app/styles/base/_toggle-switch.less
  app/styles/toggle-switch.less
Labels: reviewed/ready-to-merge

#488 Stop video when changing page for carousel
  .nvmrc
  addon/components/o-s-s/carousel.stories.js
  addon/components/o-s-s/carousel.ts
  tests/integration/components/o-s-s/carousel-test.ts
Labels: reviewed/needs-review

#489 Update email-input component's placeholder
  addon/components/o-s-s/email-input.stories.js
  addon/components/o-s-s/email-input.ts
Labels: reviewed/ready-to-merge

#494 Update attributes panel component to handle initial mode
  addon/components/o-s-s/attributes-panel.stories.js
  addon/components/o-s-s/attributes-panel.ts
  tests/integration/components/o-s-s/attributes-panel-test.ts
Labels: reviewed/needs-review

#495 Input container: Remove stopImmediatePropagation/preventDefault from paste event
  addon/components/o-s-s/input-container.ts
  tests/integration/components/o-s-s/input-container-test.js
Labels: reviewed/needs-review

#497 Add states for dropdown button
  addon/components/o-s-s/button-dropdown.hbs
  app/styles/molecules/button-dropdown.less
  tests/integration/components/o-s-s/button-dropdown-test.ts
Labels: reviewed/ready-to-merge, actions/fe-deploy-preview

#484 Update searchfield component to use it where needed
  addon/components/o-s-s/access-panel.hbs
  addon/components/o-s-s/access-panel.ts
  addon/components/o-s-s/infinite-select.hbs
  addon/components/o-s-s/infinite-select.ts
  addon/components/o-s-s/search-field.hbs
  addon/components/o-s-s/search-field.stories.js
  addon/components/o-s-s/search-field.ts
  addon/utils/keyboard.ts
  app/utils/keyboard.js
  tests/integration/components/o-s-s/access-panel-test.ts
Labels: reviewed/needs-review

#500 Make the onSearch argument of the OSS::AccessPanel optional
  addon/components/o-s-s/access-panel.hbs
  addon/components/o-s-s/access-panel.ts
  tests/integration/components/o-s-s/access-panel-test.ts
Labels: reviewed/ready-to-merge

#501 Add fallbackPlacements option to attach-dropdown
  addon/utils/attach-dropdown.ts
Labels: reviewed/ready-to-merge

#496 Fix input focus
  addon/components/o-s-s/infinite-select.hbs
  addon/components/o-s-s/infinite-select.ts
Labels: reviewed/needs-review

#503 Add docs for AccessPanel component
  addon/components/o-s-s/access-panel.stories.js
Labels: reviewed/needs-review

#491 Use portaled dropdowns for OSS::CountrySelector & OSS::PhoneNumberInput
  addon/components/o-s-s/country-selector.hbs
  addon/components/o-s-s/country-selector.ts
  addon/components/o-s-s/phone-number-input.hbs
  addon/components/o-s-s/phone-number-input.ts
  addon/components/o-s-s/private/base-dropdown.ts
Labels: reviewed/needs-review
